services:
  drill-ui:
    build:
      context: .
      args:
        VITE_DIAGRAM_API_URL: ${VITE_DIAGRAM_API_URL}
        VITE_TOIR_LIGHT_ORIGIN: ${VITE_TOIR_LIGHT_ORIGIN}
        VITE_KEYCLOAK_URL: ${VITE_KEYCLOAK_URL}
        VITE_KEYCLOAK_REALM: ${VITE_KEYCLOAK_REALM}
        VITE_KEYCLOAK_CLIENT_ID: ${VITE_KEYCLOAK_CLIENT_ID}
    expose:
      - "80"
    networks:
      - proxy

networks:
  proxy:
    external: true
